import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const jost = localFont({
  src: "../fonts/Jost-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} mx-auto flex max-w-[1100px] flex-row pt-24 text-body-1 text-secondary-dark-blue antialiased`}
      >
        <header className="max-w-[255px] md:text-black"></header>
        {children}
      </body>
    </html>
  );
}
